name: Build and deploy Pointer*

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    
env:
  version: "2.0.${{ github.run_number }}"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: dotnet build
        run: dotnet build --configuration Release --version "${{ env.version }}"

      - name: dotnet test
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage
        
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.24
        with:
          reports: coverage/**/coverage.cobertura.xml
          targetdir: coveragereport
          reporttypes: Html;MarkdownSummaryGithub
          title: 'Code Coverage'

      - name: Write PR Number
        run: |
          echo ${{ github.event.number }} > ./coveragereport/PullRequestNumber

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: CodeCoverage
          path: coveragereport/
          if-no-files-found: error
        
      - name: dotnet publish
        run: dotnet publish -c Release -p:PublishDir=${{env.DOTNET_ROOT}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{env.DOTNET_ROOT}}/publish

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pointerstar'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
